language: rust

rust:
  - beta

cache:
  directories:
    - $HOME/.cargo
    - node_modules

install:
  # Install Node via NVM.
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install lts/carbon
  # Install wasm-pack.
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

script:
  - ./build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: .
  keep-history: false
  on:
    branch: master
